all: clean
	latex brownien.tex
	latex brownien.tex
	dvipdfm brownien.dvi

clean:
	rm -rf **/*.aux
	rm -rf **/*.pdf
	rm -rf **/*.dvi
	rm -rf **/*.idx
	rm -rf **/*.ilg
	rm -rf **/*.ind
	rm -rf **/*.log
	rm -rf **/*.toc